### ISSUE TITLE
generatejson error

### ISSUE THREAD

**Issue by owenrandlett** [neurodata/ndstore#223]
Hi - I'm getting an error when trying to upload my data using the updated generatejson script. my edited version: [generatejson_ZBrain.py.zip](https://github.com/neurodata/ndstore/files/144775/generatejson_ZBrain.py.zip)

do you know what I am doing wrong? 

the error I get is: 

Traceback (most recent call last):
  File "generatejson_ZBrain.py", line 173, in <module>
    main()
  File "generatejson_ZBrain.py", line 170, in main
    ai.post_data(SITE_HOST)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ndio/utils/autoingest.py", line 537, in post_data
    self.verify_path(data, site_host, verifytype)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ndio/utils/autoingest.py", line 373, in verify_path
    ".format(token_name, response.content))
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by kunallillaney** [comment]
@owenrandlett I will have @Aeusman look at this.

**Comment by Aeusman** [comment]
@owenrandlett 
1. There is no folder labeled 'tERK001' in your Z-Brain folder
2. You use a '-' in your project name (a special character that can cause issues in the storage side of things), updates have been pushed to ndio (but not rolled) that prevent you from using these types of characters.

By default the AutoIngest object used in generatejson tests for the first slice of the channel, but since that folder doesn't exist the script fails. Better error handling for this has been added but has not yet been rolled.

**Comment by Aeusman** [comment]
@owenrandlett  Please close the issue if the problem has been resolved

**Comment by owenrandlett** [comment]
@Aeusman 

Thanks for your help - but I am afraid I am still getting the same error after fixing the things you pointed out. Attached is updated script with 'tERK001' corrected to 'Anti_tERK_001', and all '-' removed or replaced with '_' in folder names. 

[generatejson_ZBrain.py.zip](https://github.com/neurodata/ndstore/files/153065/generatejson_ZBrain.py.zip)

**Comment by kunallillaney** [comment]
Hey @owenrandlett I looked at your file and these were the issues, 

1.  channel_type is "image" not "Image"
2. No special characters in channel_names except underscore. You have a dot in "6.7FRhcrtR_Gal4_uasKaede_MeanOf12"

I went ahead and ran your script after fixing these issue and it worked like a charm. All the other channels are now ingested in neurodata. To be able to view them you will need to run the [histogram  service](http://docs.neurodata.io/ndstore/api/stats_api.html). This is an additional step as you have 16-bit data and we need values to clamp it for visualization and needs to be run for every channel because these values vary.. @alexbaden @Aeusman can you help you here.

Some sample links for your data(the data looks different because I am applying random clamping values and this will be resolved after the hist service does it's job)
http://openconnecto.me/ocp/ca/ZBrain/Anti_Gad67_MeanOf17/xy/0/0,800/0,600/1/window/0,5000/
http://openconnecto.me/ocp/ca/ZBrain/Anti_tERK_MeanOf193/xy/0/0,800/0,600/1/window/0,3000/
http://openconnecto.me/ocp/ca/ZBrain/Elavl3_GCaMP5G_MeanOf7/xy/0/0,800/0,600/1/window/0,3000/

If you can change the last remaining channel name (and the corresponding folder name on your server) I can ingest that channel for you by running the script.(There are some changes which have to be made in ndio for you to run this successfully and I think they have not been pushed to pip yet and so you will be unable to run it on your end).

This was a great opportunity to see how we can make our service better and we learned a lot from this. Thanks

**Comment by kunallillaney** [comment]
@Aeusman This is next in line for propagation.

**Comment by owenrandlett** [comment]
@kunallillaney @Aeusman 

Wonderful, thanks so much! I fixed the folder name to remove the '.' . Now "67FRhcrtR_Gal4_uasKaede_MeanOf12" and in attached script. [generatejson_ZBrain.py.zip](https://github.com/neurodata/ndstore/files/157602/generatejson_ZBrain.py.zip)

perhaps a naive question - but if someone has a data url with all of the correct folder hierarchy, why is it necessary to assign each channel separately in the script rather than just recursively add all folders as appropriate?

**Comment by jovo** [comment]
yah, maybe channel name is just automatically grabbed from the folder name?

On Thu, Mar 3, 2016 at 3:14 PM, owenrandlett <notifications@github.com>
wrote:

> @kunallillaney <https://github.com/kunallillaney> @Aeusman
> <https://github.com/Aeusman>
>
> Wonderful, thanks so much! I fixed the folder name to remove the '.' . Now
> "67FRhcrtR_Gal4_uasKaede_MeanOf12" and in attached script.
> generatejson_ZBrain.py.zip
> <https://github.com/neurodata/ndstore/files/157602/generatejson_ZBrain.py.zip>
>
> perhaps a naive question - but if someone has a data url with all of the
> correct folder hierarchy, why is it necessary to assign each channel
> separately in the script rather than just recursively add all folders as
> appropriate?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurodata/ndstore/issues/223#issuecomment-191943032>.
>



-- 
the glass is all full:  half water, half air.
neurodata.io

**Comment by kunallillaney** [comment]
@owenrandlett We always cannot assume that all the channels are going to be of the same type(as it was in your case). People might have channels of different types and our schema supports one to have 8-bit,16-bit, annotation, timeseries channels all in the same project.
What we can do is add a for loop to generatejson where it automatically calls add_channel for you with the same channel parameters based on the directory structure(I understand that it is quite cumbersome to manually add channel names when you have more than 3). We can add that code snippet for power users, for example you, but that will not be the default behavior. We would like the use to specify the channel type of each channel to avoid mistakes(since most of our users have 1-2 channels at max). What do you think?

**Comment by owenrandlett** [comment]
@kunallillaney @jovo 

Ah I see - I understand that mixed types could cause issues. But I guess it might be uncommon for people to mix data types?

In my (perhaps atypical) case, auto detecting channel names and structure would be very useful. What I have uploaded thus far is the average-across-fish stacks. Ideally we were thinking it would be great to have all of the individual fish that go into those averages available for people... which brings us to ~900 channels! I was thinking that fish could be represented as 'time' within a channel in your structure. 

Has the data now been propagated? How can I now see/access it? 

Thanks,
Owen

**Comment by Aeusman** [comment]
Hi Owen,

Did you ever propagate the data? Were you able to visualize it? - Sorry about the late response time on this, not sure why this fell through.

-Alex

**Comment by Aeusman** [comment]
@owenrandlett I'm going to close this in a week if no response, happy to discuss further though!

**Comment by owenrandlett** [comment]
@Aeusman <https://github.com/Aeusman> Sorry for the lack of response --
I believe I propagated the data, but I don't know if it worked. I have not
been able to visualize it.

**Comment by Aeusman** [comment]
(Pulled from @kunallillaney response above)
http://openconnecto.me/ocp/ca/ZBrain/Anti_Gad67_MeanOf17/xy/0/0,800/0,600/1/window/0,5000/
http://openconnecto.me/ocp/ca/ZBrain/Anti_tERK_MeanOf193/xy/0/0,800/0,600/1/window/0,3000/
http://openconnecto.me/ocp/ca/ZBrain/Elavl3_GCaMP5G_MeanOf7/xy/0/0,800/0,600/1/window/0,3000/

There is documentation about how to use the web browser (RESTful) interface [here](http://docs.neurodata.io/ndstore/api/data_api.html#get-xy-slice-cutout)
