### ISSUE TITLE
error on aws upload for clarity

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#367]
```
(ndstore)alex@brainviz1:~/ndstore/scripts$ python aws_interface.py Fear199 --action upload 
Inserting Cube 0 at res 5 [0, 0, 0]
An error occurred (ResourceNotFoundException) when calling the PutItem operation: Requested resource not found
Traceback (most recent call last):
  File "aws_interface.py", line 197, in <module>
    main()
  File "aws_interface.py", line 181, in main
    aws_interface.uploadExistingProject(result.channel_name, result.resolution)
  File "aws_interface.py", line 145, in uploadExistingProject
    raise e
botocore.exceptions.ClientError: An error occurred (ResourceNotFoundException) when calling the PutItem operation: Requested resource not found
```

Trying to track this down... @kunallillaney any ideas?

**Comment by alexbaden** [comment]
Full trace:
```
-> self.cuboidindex_db.putItem(ch.getChannelName(), cur_res, x, y, z)
(Pdb) l
134                     morton_index = ndlib.XYZMorton([x, y, z])
135     
136                     print "Inserting Cube {} at res {}".format(morton_index, cur_res), [x,y,z]
137                     import pdb; pdb.set_trace() 
138                     # updating the index
139  ->                 self.cuboidindex_db.putItem(ch.getChannelName(), cur_res, x, y, z)
140                     # inserting the cube
141                     self.s3_io.putCube(ch, cur_res, morton_index, blosc.pack_array(data))
142                   
143                   except Exception as e:
144                     # checkpoint the ingest
(Pdb) n
An error occurred (ResourceNotFoundException) when calling the PutItem operation: Requested resource not found
ClientError: ClientEr... found',)
> /var/www/ocp/ndstore/scripts/aws_interface.py(139)uploadExistingProject()
-> self.cuboidindex_db.putItem(ch.getChannelName(), cur_res, x, y, z)
(Pdb) c
Traceback (most recent call last):
  File "aws_interface.py", line 198, in <module>
    main()
  File "aws_interface.py", line 182, in main
    aws_interface.uploadExistingProject(result.channel_name, result.resolution)
  File "aws_interface.py", line 139, in uploadExistingProject
    self.cuboidindex_db.putItem(ch.getChannelName(), cur_res, x, y, z)
botocore.exceptions.ClientError: An error occurred (ResourceNotFoundException) when calling the PutItem operation: Requested resource not found
```

**Comment by kunallillaney** [comment]
This has now been resolved. You have the email with working links for data. IAM credentials are also sorted.
